<?php
    if(!isset($_SESSION))
    {
        session_start();
    }
    include("../Classes/connect.php");
    include("../Classes/login_class.php");
    include("../Classes/user.php");
    include("../Classes/post_class.php");
    include("../Classes/image.php");
    include("../Classes/signup_class.php");
    include("../Classes/profile_class.php");
    include("../Classes/settings.php");
    include("../Classes/time.php");
    include("../Classes/functions.php");